---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - database.mohitnagaraj.in
  resources:
  - databasemigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.mohitnagaraj.in
  resources:
  - databasemigrations/finalizers
  verbs:
  - update
- apiGroups:
  - database.mohitnagaraj.in
  resources:
  - databasemigrations/status
  verbs:
  - get
  - patch
  - update
