apiVersion: database.mohitnagaraj.in/v1alpha1
kind: DatabaseMigration
metadata:
  labels:
    app.kubernetes.io/name: kube-shift
    app.kubernetes.io/managed-by: kustomize
  name: databasemigration-sample
spec:
  # TODO(user): Add fields here
