apiVersion: database.mohitnagaraj.in/v1alpha1
kind: DatabaseMigration
metadata:
  labels:
    app.kubernetes.io/name: kube-shift
    app.kubernetes.io/managed-by: kustomize
  name: bluegreen-migration-sample
  namespace: default
spec:
  database:
    type: postgresql
    connectionSecret: postgres-credentials
    host: postgres.default.svc.cluster.local
    port: 5432
    database: productiondb
    sslMode: require
    
  migration:
    strategy: blue-green
    scripts:
      - name: schema-upgrade-v2
        type: schema
        source: configmap://migrations/bluegreen_001_schema_v2.sql
        timeout: 10m
      - name: data-migration-v2
        type: data
        source: configmap://migrations/bluegreen_002_data_v2.sql
        dependsOn: ["schema-upgrade-v2"]
        timeout: 30m
      - name: final-validation
        type: validation
        source: configmap://migrations/bluegreen_003_validate_v2.sql
        dependsOn: ["data-migration-v2"]
        timeout: 5m
    parallel: false
    batchSize: 2000
    
  validation:
    preChecks:
      - type: connection
      - type: permissions
      - type: disk-space
        threshold: 50GB
    dataIntegrityChecks:
      enabled: true
      samplePercentage: 20
      checksumValidation: true
    performanceThresholds:
      maxMigrationTime: 60m
      maxDowntime: 0s
      maxCpuUsage: 70%
      maxMemoryUsage: 60%
      
  rollback:
    automatic: true
    conditions:
      - data-corruption
      - performance-degradation
      - timeout
    strategy: immediate
    preserveBackup: true
    
  notifications:
    slack:
      webhook: bluegreen-slack-webhook-secret
    email:
      recipients: ["dba@company.com", "devops@company.com", "cto@company.com"] 